### ISSUE TITLE
Gameplay won't reset at 1.0 game speed

### ISSUE THREAD

**Issue by antoniu200** [nlgzrgn/NFSCExOpts#13]
Hi! So, I was screwing around with the game speed in NFS Carbon, set it to .8, then .95 and then back to 1.0. Yesterday, the gameplay seemed fine at 1.0, but today when I launched a race, it seemed slower. Went in the mod and set the game speed to 1.2, the game speed seemed much better, a liitel bit faster, but only noticeable at the end of the race. I could keepo it that way, but the speedbreaker won't work correctly. Any help?

**Comment by DiamondMaster07** [comment]
I'm pretty sure it went on normal speed on 1.0, it has no reason to be slower/faster unless the value is changed

**Comment by antoniu200** [comment]
I don't know, to me it doesn't seem like it. The countdown is off and the car looks slower. It is very noticeable at the end of the race, when that animation ends. The animations are not synced with the sounds. I checked some videos on YouTube, just to be sure I'm not seeing things, but I'm not. And the GameSpeed is set to 1.0.

**Comment by antoniu200** [comment]
Just so I eliminate a possibility, the game is not lagging. I have a GTX 989 and a Xeon X5650 with 12 GB of RAM. I had to enable vSync so I won't get tearing.

**Comment by DiamondMaster07** [comment]
Can you record something, like a race start(with sound)?

**Comment by antoniu200** [comment]
Of course, but tomorrow. Now I'm tired. I also just shut off my PC. Just so I know in time, what is the maximum file size that GitHub allows (I'm on mobile right now)?

**Comment by DiamondMaster07** [comment]
You can upload it as an unlisted video on YT and put the link here

**Comment by AeroWidescreen** [comment]
No offense, but it's most likely your imagination or a mistake you made. All it does is change the value of 00A712AC to whatever you set in your ini. I confirm the default value is 1.0.

**Comment by antoniu200** [comment]
@AeroWidescreen I am not saying it is not 1.0, I know it is too, but what I'm saying is something got screwed up. Did you make sure the game doesn't change any other values on its own when messing with the GameSpeed? Because I know very well what I have changed. I will attach you tonight my .exe (I modified some cars with VltEd, so the size may not be the common one), the .asi, the .ini and the A/V recording of a race in the game.

**Comment by AeroWidescreen** [comment]
I admittedly don't know C++, but I'm pretty sure that it's writing the float value set for GameSpeed to address 00A712AC, just as the code above that does for WorldAnimationSpeed. There's nothing else being done for GameSpeed that I could find.

https://github.com/nlgzrgn/NFSCExOpts/blob/master/NFSCExtraOptions/dllmain.cpp#L854
`injector::WriteMemory<float>(0xA712AC, GameSpeed, true);`

I also checked the memory address to make sure the value was being set correctly and nothing else was being changed. That's why I think it might be something else causing it, but I'll wait for your video to get a better idea of what's happening.

**Comment by antoniu200** [comment]
I have a question in this case: could a CPU that's been underclocked cause this? I usually keep my CPU at 3.5 GHz, but yesterday I had a power outage and my motherboard usually resets the higher clocks on such ocasions. And the normal clock for my CPU is 2.66 GHz. Could this be it?

**Comment by antoniu200** [comment]
It seems to be back to normal now, I'll try to underclock my CPU to 2.66 GHz and see what that does.

**Comment by antoniu200** [comment]
Great, I cannot recreate it… At this point, I look like a liar.

**Comment by DiamondMaster07** [comment]
Well, if it works correctly now, then case closed! 😉

**Comment by AeroWidescreen** [comment]
I don't think anyone thinks you're lying, but there's so many possibilities it's hard to say what was causing it. Glorious PC gaming I guess. If it happens again try removing Extra Options and see if that fixes it. At least it's working now though.

**Comment by antoniu200** [comment]
I did try removing ExOpts yesterday. Well, thanks for trying to help anyway.
