### ISSUE TITLE
Config settings not working on Windows 10

### ISSUE THREAD

**Issue by GTR-GUNS** [nlgzrgn/NFSCExOpts#18]
I went to enable a bunch of fun stuff, but when I go to save it, I'm greeted by a text box, saying I do not have permission. I'm like, Bitch? So now what? I'm lost.

Things I have tried:
-Editing stuff
-Changing the permissions
-Replacing the file (That just caused a nuclear war between my GPU and my CPU for some strange reason)
-Posting on GitHub

**Comment by GTR-GUNS** [comment]
So I've fixed it. 
Steps taken:
-Reinstall all the files (Casued a lot of pain, only to find it did nothing)
-Slapped the wall a few times
-Threw a brick
-opened a bunch of stuff in total rage
-Restarted my PC a few too many times (Got the nuclear war between my GPU and CPU to end (CPU obvs. won))
-Had a bird shit all over my clean hoodie
-Set the permissions properly, and unblocked it
-Now it works and there's no more nuclear war ;)

**Comment by GTR-GUNS** [comment]
Someone that knows how, please close this. 👍 
🥇

**Comment by GTR-GUNS** [comment]
Still broken

**Comment by GTR-GUNS** [comment]
What am I doing wrong? Nothing I do changes anything. I want the infinite autosculpt so I can finish my drag car >:(

**Comment by JUMBO95** [comment]
Hey first reinstall nfs classic 1.4 no collector edition then use FIRST widescreen fix and then extra options. ITS Work for me.

**Comment by GTR-GUNS** [comment]
How would I do that?

How do I know it is the collectors edition? xD

**Comment by JUMBO95** [comment]
play the game and see if there's Koenigsegg CCX in quick race menu

**Comment by GTR-GUNS** [comment]
There is no koenigsegg CCX in the quick race menu.

**Comment by JUMBO95** [comment]
Ok uninstall game with remove utility iobit uninstaller or any uinstaller tool for completely uninstall game from your PC. Then install game from there its full game with 1.4 patch zou dont need any crack http://igg-games.com/need-for-speed-carbon-pc-free-download.html

Then install widescreen fix FIRST!!!! https://github.com/ThirteenAG/WidescreenFixesPack/releases/tag/nfsc

copy all files to game folder
Then copy Extra options to script folder and  dinput8.dll 
If you have antivirus make sure you  allow script folder and dinput8.dll

**Comment by GTR-GUNS** [comment]
Sweet. Thanks  :D
