### ISSUE TITLE
Game crash on launch.

### ISSUE THREAD

**Issue by Nightstar18** [nlgzrgn/NFSCExOpts#3]
I installed everything like it was explained, then i tried launching the game. It didn't work so i looked for a different NFSC.exe file online (I did this with the Most wanted version aswell and it worked). It ran once and once only. I then crashed the game by messing around with the debug custom car creator. After that the game didn't want to launch anymore :( . I removed the scripts folder and it worked normally without the extra stuff. I tried putting a new scripts folder back in and it still didn't want to work.

Please help. I really love these carbon mods. :'(

**Comment by Nightstar18** [comment]
I got it working XD

For some reason when i set "disabletakeover" to 1, the game works fine! 
what is life?  \_0_0_/

**Comment by nlgzrgn** [comment]
Sorry for the late comment but as I see, this issue is a dupe of #1 

I've fixed this one with v2.0.1.1337 (Build 2; Rev.01). Please tell me which version you've used when you've caught this issue.

> what is life? _0_0_/
Dunno b'coz I'm dead inside. :(
