### ISSUE TITLE
Autosculpt?

### ISSUE THREAD

**Issue by asybal** [nlgzrgn/NFSCExOpts#6]
Hey! I installed the mod, the vinyl works well but the autosculpt,rideheight etc doesn't work can you help me with this issue??

**Comment by nlgzrgn** [comment]
Hey! Did you try enabling "InfiniteAutosculptSliders" option from NFSCExtraOptionsSettings.ini? If so, can you launch your game as administrator?

**Comment by asybal** [comment]
Hello! thank you for the replies! can you show me how to enable the "InfiniteAutosculptSliders"?
i played the game on administrator mode, Thanks a lot for replying!!

**Comment by nlgzrgn** [comment]
Open NFSCExtraOptionsSettings.ini in Notepad.
Locate "InfiniteAutosculptSliders" value. You can find it on [Menu] section.
Replace the 0 with 1.
Save the file. (If you get an "Access Denied" error, save the file to desktop instead. Copy it and paste it to your NFSC Installation Directory\scripts. Override the file.
Run the game and install any autosculpt you want.

![NFSCExtraOptionsSettings.ini in Notepad](https://cloud.githubusercontent.com/assets/1937572/24416669/435498b2-13ee-11e7-901b-9c3f1683c957.png)

**Note that there is a known issue abut that: When this option is enabled, you may get crashes on "Options" screen sliders.**

**Comment by nlgzrgn** [comment]
test

**Comment by asybal** [comment]
Thanks! the game run smoothly no crashes thank you soo much for the replies!!

**Comment by nlgzrgn** [comment]
So I can close this issue happily now! You're welcome. :D
